coinbase/mesh-specifications

README.md, api.json, api.yaml, codegen.sh, models/Curve.yaml, models/CurveType.yaml, models/PublicKey.yaml, models/Signature.yaml, models/SignatureType.yaml, models/SigningPayload.yaml
To support universal writes to any blockchain, we need to introduce a new collection of endpoints to complement our existing `Data API` ones.
Add support for generic transaction construction using the new endpoints (which must work entirely offline):
* `/construction/derive`
* `/construction/preprocess`
* `/construction/payloads`
* `/construction/combine`
* `/construction/parse`
* `/construction/hash`
In addition to the existing endpoints (which can be online):
* `/construction/metadata`
* `/construction/submit`
```
Caller (i.e. Coinbase)                              + Data API Implementation
+------------------------------------------------------------------------------------+
X                                                      |
X      Get Supported Networks …
```
=> Add Construction API (formerly Wallet API)

api.json, models/Error.yaml
(Opening up as a PR directly with the suggested change to clarify this point for implementations and clients but happy to discuss if this isn't the actual intention of the Error Code/Message distinction.)
This makes it explicit that the Code attribute of the Error model is the
authoritative source of truth for the origin of the error, while the
error message is secondary.
It also makes it explicit that the same error code may present multiple
different messages so clients of Rosetta implementations should not rely
on them for error detection and Rosetta backends should make an effort
to present error codes in a granular enough level for clients.
=> Define Error.Code as authoritative

api.json, api.yaml, models/Block.yaml
This adds a requirement that all calls to the /block endpoint be
idempotent when identifying a block by hash.
This ensures blocks are inalterable and clients can safely assume that
once they've received a specific block from a Rosetta implementation
that block won't change.
The discussion that prompted this is [here](https://community.rosetta-api.org/t/on-the-universality-and-uniqueness-of-the-tx-hash-identifier/81)
=> Add /block idempotency requirement

api.json, api.yaml
=> TransactionIdentifierResponse + change default status to 500

api.json, api.yaml, models/Coin.yaml, models/CoinAction.yaml, models/CoinChange.yaml, models/CoinIdentifier.yaml, models/Operation.yaml
To support automatic testing of UTXO-based chains, we need greater visibility into the creation and destruction of "coins". This PR adds support for doing so with the concept of the `Coin`. Generic UTXOs in Rosetta have a `coin_identifier`, which can be any string (ex: Bitcoin would be `tx_hash:index`), and can be created or spent with `CoinAction`.
Because of this modeling abstraction, it is possible to support both UTXO-based transfers and account-based transfers at the same time.
Related Issue: #28
=> Add Coin Model

api.json, api.yaml, models/SyncStatus.yaml
Fixes #27 
Fixes https://github.com/coinbase/rosetta-cli/issues/63
When a node is not queryable until some sync phase is complete, it is difficult to tell if the node is stalled (all that is visible is the current queryable block). This PR adds support for providing more detail on the syncing process (optional).
=> Support Pre-Query Status

api.json, api.yaml
The Rosetta API does not support dynamic fees very well. This PR adds support for specifying fee and viewing the suggested fee (according to provided intent and network conditions).
=> Improved Fee Handling

api.json, api.yaml
This PR adds additional documentation around how network-specific `Metadata` should be provided to the `Construction API`.  Many of the additional details here were provided in response to discussions on the community: https://community.rosetta-api.org/t/rosetta-cli-check-construction-dynamic-parameter/145?u=patrick.ogrady
=> Add more details about Metadata population

api.json, api.yaml
In some blockchains, blocks may be "omitted" at certain indexes (i.e. skipped). In this case, the `BlockResponse.Block` should be left unpopulated.
It is VERY important to note that blocks MUST still form a canonical, connected chain of blocks where each block has a unique index. In other words, the `PartialBlockIdentifier` of a block after an omitted block should reference the last non-omitted block.
Related Post: https://community.rosetta-api.org/t/what-rosetta-expects-as-block-response-when-a-block-was-not-produced/156
Related PRs:
* https://github.com/coinbase/rosetta-sdk-go/pull/91
* https://github.com/coinbase/rosetta-cli/pull/98
=> Support Omitted Blocks

api.json, models/Operation.yaml, models/OperationIdentifier.yaml
Credit to @metajack for finding this one!
The `Operation.RelatedOperations` example was completely wrong. This made the `Operation` example particularly hard to understand (it looked like there was an extra index in there somehow)!
=> Fix RelatedOperations example

api.json, api.yaml
Closes: #43 
Additional Context: https://community.rosetta-api.org/t/any-way-to-get-public-key-from-signer-package-before-combine/189
In some blockchains, transaction construction requires the `PublicKey` of some `AccountIdentifiers` present in a transaction.
This PR allows a Rosetta implementation to request the `PublicKey` of any number of `AccountIdentifiers` in the `/construction/preprocess` response. The caller can then provide the requested `PublicKeys` in a call to `/construction/payloads` so that construction can be completed.
=> Access PublicKeys During Construction

README.md, api.json, api.yaml
Related PR: #45 
Some blockchains require the PublicKey to fetch metadata for transaction construction. This PR allows for passing the requested PublicKeys into `/construction/metadata`.
=> Provide PubKeys to /construction/metadata

README.md, api.json, models/CurveType.yaml, models/SignatureType.yaml
Fixes # .
Enables support for Coda Protocol's rosetta implementation, specifically the curve type and signature scheme used in Coda.
Adds Coda's curve type (tweedle) and signature scheme (schnorr_poseidon) to the specification.
=> Support Coda with Tweedle curve and SchnorrPoseidon signatures

api.json, api.yaml, models/SigningPayload.yaml
Closes #47 
This PR deprecates all string `Address` field and replaces them with `AccountIdentifier`. This PR **DOES NOT** break any existing implementations (who will just continue populating `Address-based` fields unless they need extra expressivity).
=> Deprecate Address-based Fields

api.json, models/Operation.yaml
Fixes # .
Operation types are now specified in `NetworkOptionsResponse`, rather than `NetworkStatus`
=> updated types field description in Operation

api.json, api.yaml
@matheusd brought up the strange lack of "required" parity between `ConstructionPreprocessResponse.Options` and `ConstructionMetadataRequest.Options` in https://github.com/coinbase/rosetta-sdk-go/pull/166. This was originally intended so the caller to opt to avoid calling `/construction/metadata` if there were no `ConstructionPreprocessResponse.Options`.
As a result of the conversation on that PR, we've decided it is best to not make `Options` required in `ConstructionMetadataRequest` in the case that an implementer does not need to pass any info related to the `/construction/preprocess` execution. As a side note, this means we can remove the conditional nature of the `Construction API` flow.
=> [Construction] Options Parity

README.md
This PR adds `/call` to the list of online endpoints in the `README`.
=> README Nits

api.json, api.yaml, models/Allow.yaml, models/BalanceExemption.yaml, models/ExemptionType.yaml
Fixes: #53 
This PR adds support for "exempting" account balances identified by a certain `SubAccount.Identifier` or `Currency` from strict balance tracking (instead subjecting them to tracking that reflects the specified `ExemptionType`). In other words, it is now possible to specify which account balances may change without corresponding operations (i.e. staking rewards, vesting balances, tokens with dynamic supply).
`BalanceExemptions` should be used sparingly as they may introduce significant complexity for integrators that attempt to reconcile (compare computed balance with live balance) the balance of accounts they care about.
=> Support Account Balance Tracking "Exemptions"

api.json, api.yaml, models/Allow.yaml
This PR adds `timestamp_start_index` to `NetworkOptions.Allow` so that implementers can exempt some initial number of blocks from timestamp assertion (usually when the genesis block has a timestamp of 0).
=> Add timestamp_start_index

api.json, models/Error.yaml
Fixes #59 
This PR adds a new `description` field to the `Error` model. You can checkout the linked issue for the inspiration for this addition.
=> Error Descriptions

README.md
This PR updates the README to include `rosetta-bitcoin` and `rosetta-ethereum`.
=> Update README with reference implementations

api.json, api.yaml, models/Operation.yaml
Related: https://github.com/coinbase/rosetta-cli/issues/180
This PR updates `Operation.Status` to be considered optional. We've been treating this field as optional since the introduction of the Construction API ("intent" should not have a populated `Operation.Status`) but have yet to update the spec to reflect this.
=> Make `Operation.Status` optional

api.json, api.yaml
This PR adds support for specifying that only a subset of balances and coins be returned for a particular AccountIdentifier. This can be particularly effective for a Rosetta Module that supports hundreds of tokens (each requiring a call to the node to get balance)!
=> /account/balance + /account/coins restricted queries

README.md, api.json, api.yaml, models/BlockEvent.yaml, models/BlockEventType.yaml, models/BlockTransaction.yaml, models/Operator.yaml
This PR adds support for standard "indexer" endpoints (optional for any Rosetta implementation to complete). Anyone can write a compliant Rosetta Indexer by supporting these new endpoints and clients can access any of these indexers without a separate SDK.
=> Indexer Endpoints

api.json, api.yaml, models/Operator.yaml
This PR makes `operator` an optional field on `SearchTransactionsRequest`. In short, this change was made because supplying an `operator` when there is only 1 condition provided can be quite confusing.
=> `SearchTransactionsRequest.Operator` Optional

api.json, api.yaml
Closes: #69 
This PR adds a new `total_count` field to the `SearchTransactionResponse`. This enables callers to concurrently fetch search results.
=> [indexer] Add `total_count` field

api.json, api.yaml, models/Operation.yaml, models/SyncStatus.yaml
This PR introduces a new field to `SyncStatus` that lets implementations return a boolean indicating if they are fully synced. This field is particularly useful for quiescent blockchains (blocks only produced when there are pending transactions). In these blockchains, the most recent block could have a timestamp far behind the current time but the node could be at tip.
=> Return `Synced` Status

api.json, api.yaml, models/Direction.yaml, models/RelatedTransaction.yaml
Adds support for the planned related transaction feature that will allow linking of multiple transactions within rosetta.
Transactions will now feature an optional related_transactions array of RelatedTransaction objects. Related Transaction objects feature a network_identifier (optional), transaction_identifier, and direction (forward or backward). This was done to provide support for multiple relations of different directions across multiple networks if necessary.
N/A
=> Add Support for Related Transactions

api.json, models/SigningPayload.yaml
Description for hex-bytes was missing in the SigningPayload doc.
=> [PROTO-903] Add description for hex-bytes in SigningPayload

api.json, models/SyncStatus.yaml
Found while reviewing the latest version.
=> Fix typo in SyncStatus

api.json, api.yaml
Some chains don't have `peers` in `/network/status` response and the system allows for it to be empty. However, it shows up as required. 
Remove `peers` from the required fields for NetworkStatusResponse.
=> Remove `peers` as a required field in NetworkStatusResponse

api.json, api.yaml
Removed `peers` as a required field for NetworkStatusResponse.
=> (chore) Update API version to 1.4.13

api.json, api.yaml
Fixes # .
remove public key field in ConstructionMetadataRequest
=> remove public key in metadata

api.json, api.yaml
Fixes # .
these two fields are conflict add complex in our internal services
and sometimes make the return dynamic fee unreliable
=> [preprocess]remove max_fee and mulltiplier in preprocess request

api.json, models/CurveType.yaml, models/SignatureType.yaml
Rosetta does not support Bitcoin's [BIP-340 Schnorr](https://github.com/bitcoin/bips/blob/master/bip-0340.mediawiki) signing scheme.
Update Rosetta's specifications to include the `secp256k1_bip340` Curve Type and `schnorr_bip340` Signature Type. This will subsequently enable the addition of BIP-340 support to [Rosetta SDK Go](https://github.com/coinbase/rosetta-sdk-go).
---
More on the technical details, benefits and relevant discussions around adding BIP-340 support can be found via the following links:
- https://github.com/coinbase/rosetta-specifications/discussions/113
*(via #112)*
- https://community.rosetta-api.org/t/question-about-rosetta-sdk-go-prs
=> Add Support for BIP-340 Schnorr

api.json, api.yaml
The current version is not correct. We did a 1.4.15 release, but then that we serve the '1.4.13' string from the api.json which messes with the mesh-sdk-go update.
Hence, I'll merge this, and then make a new `1.5.1` release where the api.json and api.yaml version
=> Bump version to 1.5.1
